### ISSUE TITLE
Programmatically accessing the latest csv data

### ISSUE THREAD

**Issue by agitter** [ebmdatalab/covid_trials_tracker-covid#18]
Your COVID-19 Trials Tracker look like a perfect resource for a collaborative project I'm part of.  A team of us are writing a review manuscript about COVID-19 diagnostics and therapeutics.  The manuscript is written with [Manubot](https://manubot.org/) so we're now working to include figures or tables that automatically update every time the manuscript is built.  The high-quality data and nicely-formatted csv you've made available at http://covid19.trialstracker.net/ are a great fit.

What is the best way to programatically download the latest version of the csv data file?  The button at http://covid19.trialstracker.net/ appears to include some dynamic information or session data.  Is the csv file in the https://github.com/ebmdatalab/covid_trials_tracker-covid/tree/master/notebooks/this_weeks_data directory a good option?

If you want to learn more about how we intend to use this, please see:
- Related issue: https://github.com/greenelab/covid19-review/issues/406
- Manuscript draft: https://greenelab.github.io/covid19-review/
- Project repository: https://github.com/greenelab/covid19-review

Thanks for the great resource.

**Comment by NickCEBM** [comment]
Hi @agitter!

Sorry I didn't see this sooner.

The easiest way to programatically download the latest CSV would be to point your software to here:
https://github.com/ebmdatalab/covid_trials_tracker-covid/tree/master/notebooks/tableau_data

That's a final version of the CSV that perfectly matches what you would get from download the CSV on the website that updates with the same file name each week.

The CSV is also here:
https://github.com/ebmdatalab/covid_trials_tracker-covid/tree/master/notebooks/processed_data_sets

But the name changes for each archived CSV, so that may be difficult to locate the most recent programatically.

If you don't mind JSON format, this would also work:
https://github.com/ebmdatalab/covid_trials_tracker-covid/blob/master/notebooks/website_data/trials_latest.json

Do not use the following as this is the raw pre-processed ICTRP data:
https://github.com/ebmdatalab/covid_trials_tracker-covid/tree/master/notebooks/this_weeks_data

Let me know if any other questions!

**Comment by NickCEBM** [comment]
One other thing to note! Reading over your issue about how you might use the data, just so you know the data on interventions is extracted manually by me at the point of entry into the database. It's not dual-coded (don't have the resource for that right now) so there probably is some error-rate there (although I try my best!). So that means:

1. If the list of interventions somehow changes or updates, it might not be pulled through (I expect this to be rare)

2. My list of interventions used in each study is all those listed even if it isn't the primary therapy being examined. So all those trials of say, hydroxychloroquine, include studies in which it is being used as an active comparator or standard of care.

You may have already figured this out but wanted to make sure you understood that upfront!

**Comment by agitter** [comment]
Thanks for the thorough response @NickCEBM.  Either the CSV or the JSON should work for what I have in mind.  I appreciate the additional clarifications about interventions as well.

I'll report back to let you know what we did with the data.

If we cite this data source, is the list of contributors at http://covid19.trialstracker.net/about/ the best list of authors to include?

**Comment by NickCEBM** [comment]
I'd say cite our Zenodo repo which I'll probably throw an updated release into soon:

https://zenodo.org/record/3732709

**Comment by NickCEBM** [comment]
Also, I'd say if you don't mind the JSON, use that as who knows if our Tableau data feed might change at some point. 

However that JSON file will always be what drives the table on the website.

**Comment by agitter** [comment]
Thanks for the additional advice.  I'm planning to read it into a pandas dataframe, so JSON will work.

**Comment by agitter** [comment]
Thanks for the help with this @NickCEBM.  A figure based on data from this repo is now in our draft manuscript: https://greenelab.github.io/covid19-review/#fig:ebm-trials  We have a nightly cron job that pulls the latest JSON data from this repo and regenerates the figure.

I cited the Zenodo DOI as you suggested: https://greenelab.github.io/covid19-review/#ref-SSbnPnzT

Is it okay if I acknowledge your help setting this up in our manuscript?

**Comment by NickCEBM** [comment]
That's great! Very happy you were able to use the data. Working on the next refresh now.

Yes, please feel free to acknowledge @agitter . Very kind of you. 

Is your pipeline dependent on the data structure looking exactly the same? I might be re-doing the results columns, and adding a new field or two, in the near future. Happy to give you a heads up when I've done that.

**Comment by agitter** [comment]
> Is your pipeline dependent on the data structure looking exactly the same?

I didn't see how to extract column headers from the JSON file, so currently that part is hard-coded.  If the column order changed but the number of columns remained the same, that could break my code.  If the number of columns changed, my build would fail so I would notice that I need to update the header names.

Besides that, my pipeline should be pretty robust.  I'll close this issue because it has been addressed, but it would be helpful if you tag me here again if you make updates to the data frame structure.  Thanks again for all your help.

**Comment by NickCEBM** [comment]
@agitter just a heads up that this update I'm about to merge in will add a column for "acronym"

**Comment by agitter** [comment]
Thanks for letting me know.  I updated our script to accept the additional column.
